FROM node:22-alpine AS build

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml nx.json tsconfig.base.json tsconfig.json ./
COPY web ./web
COPY contracts ./contracts

RUN corepack enable
RUN pnpm config set dangerously-allow-all-builds true && pnpm install --frozen-lockfile
RUN pnpm add -D vite@8.0.14 --filter web
RUN pnpm rebuild
RUN pnpm nx sync
RUN pnpm nx build contracts
RUN pnpm nx build web

FROM nginx:alpine

COPY --from=build /app/web/dist /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx","-g", "daemon off;" ]